
export const ADD_BIKE = "ADD_BIKE ";
export const DELETE_BIKE = "DELETE_BIKE";
export const EDIT_BIKE = "EDIT_BIKE";
export const MARK_BIKE = "MARK_BIKE";
export const MARK_ALL = "MARK_ALL";
export const CLEAR_MARKED = "CLEAR_MARKED";
export const METAMASK = "METAMASK";

//Create project action types
export const CREATE_PROJECT_CHANGE_COUNTRY_CODE = "CREATE_PROJECT_CHANGE_COUNTRY_CODE";
//Crowd fund project action types
export const CROWDFUND_PROJECT_CHANGE_COUNTRY_CODE = "CROWDFUND_PROJECT_CHANGE_COUNTRY_CODE";


// List Bikes action types
export const FETCH_LIST_BIKES_BY_COUNTRY_CODE = "FETCH_LIST_BIKES_BY_COUNTRY_CODE";
export const FETCHING_LIST_BIKES = "FETCHING_LIST_BIKES";
export const FETCH_LIST_BIKES_FAILED = "FETCH_LIST_BIKES_FAILED";
export const FETCH_LIST_BIKES_SUCCESS = "FETCH_LIST_BIKES_SUCCESS";

//Crowdfund list bikes
export const FETCH_LIST_CROWDFUND_BIKES_BY_COUNTRY_CODE = "FETCH_LIST_CROWDFUND_BIKES_BY_COUNTRY_CODE";
export const FETCHING_LIST_CROWDFUND_BIKES = "FETCHING_LIST_CROWDFUND_BIKES";
export const FETCH_LIST_CROWDFUND_BIKES_FAILED = "FETCH_LIST_CROWDFUND_BIKES_FAILED";
export const FETCH_LIST_CROWDFUND_BIKES_SUCCESS = "FETCH_LIST_CROWDFUND_BIKES_SUCCESS";

//Bike action types
export const CREATE_BIKE_DAO = "CREATE_BIKE_DAO";
export const CREATE_BIKE_DAO_FAILED = "CREATE_BIKE_DAO_FAILED";
export const CREATE_BIKE_DAO_SUCCESS = "CREATE_BIKE_DAO_SUCCESS";

//Term wrapper action types
export const TERM_WRAPPER_LOAD_TERMS = "TERM_WRAPPER_LOAD_TERMS";
export const TERM_WRAPPER_LOAD_TERMS_SUCCESS = "TERM_WRAPPER_LOAD_TERMS_SUCCESS";
export const TERM_WRAPPER_LOAD_TERMS_FAILED = "TERM_WRAPPER_LOAD_TERMS_FAILED";

export const TERM_WRAPPER_LOAD_BIKE_MODEL = "TERM_WRAPPER_LOAD_BIKE_MODEL";
export const TERM_WRAPPER_LOAD_BIKE_MODEL_SUCCESS = "TERM_WRAPPER_LOAD_BIKE_MODEL_SUCCESS";
export const TERM_WRAPPER_LOAD_BIKE_MODEL_FAILED = "TERM_WRAPPER_LOAD_BIKE_MODEL_FAILED";

export const FETCHING_DATA_BIKE = "FETCHING_DATA_BIKE";
export const FETCHING_DATA_LIST_BIKE = "FETCHING_DATA_LIST_BIKE";
export const FINISHED_FETCHING_DATA = "FINISHED_FETCHING_DATA";

export const UNMOUNT_BIKE_MODEL = "UNMOUNT_BIKE_MODEL";

export const FETCH_LIST_YOURS_BIKES = "FETCH_LIST_YOURS_BIKES";
export const FETCH_LIST_YOURS_BIKES_FAIL = "FETCH_LIST_YOURS_BIKES_FAIL";

export const ADD_ETHEREUM_KEY = "ADD_ETHEREUM_KEY";

export const ADD_NEW_TOAST = "ADD_NEW_TOAST";

export const RESET_TOAST = "RESET_TOAST";
