let target = {
    CREATE: "BIKES.CREATE",
    USER_INIT: "BIKES.USER_INIT",
    NETWORK_INIT: "BIKES.NETWORK_INIT",
    LOAD_BIKES: "BIKES.LOAD_BIKES",
    UPDATE: "BIKES.UPDATE",
    DESTROY: "BIKES.DESTROY",
    TRANSFER: "BIKES.TRANSFER",
    FINISH_TRANSFER: "BIKES.FINISH_TRANSFER",
    LOAD_OWNER_BIKES: "BIKES.LOAD_OWNER_BIKES",
    LOAD_NETWORK_BIKE: "BIKES.LOAD_NETWORK_BIKE",
    FINISH_UPLOAD_TO_IPFS: "BIKES.FINISH_UPLOAD_TO_IPFS",
    UPLOAD_TO_IPFS: "BIKES.UPLOAD_TO_IPFS",
    FINISH_UPLOAD_MODIFIED_TO_IPFS: "BIKES.FINISH_UPLOAD_MODIFIED_TO_IPFS",
    UPLOAD_MODIFIED_TO_IPFS: "BIKES.UPLOAD_MODIFIED_TO_IPFS",
    RESET_YOUR_BIKES: "BIKES.RESET_YOUR_BIKES",
    RENT_BIKE: "BIKES.RENT_BIKE",
    RETURN_BIKE: "BIKES.RETURN_BIKE",
    ADJUST_BIKE_PRICE: "BIKES.ADJUST_BIKE_PRICE",
    FINISH_RENT_BIKE: "BIKES.FINISH_RENT_BIKE",
    FINISH_ADJUST_BIKE_PRICE: "BIKES.FINISH_ADJUST_BIKE_PRICE",
    FINISH_RETURN_BIKE: "BIKES.FINISH_RETURN_BIKE",
    CANCEL_ADJUST_BIKE_PRICE: "BIKES.CANCEL_ADJUST_BIKE_PRICE",
    CHANGE_BIKE_FORENT_STATUS: "BIKES.CHANGE_BIKE_FORENT_STATUS",
};
let handler = {
    get: (target, key) => {
        if (target.hasOwnProperty(key)) return target[key];
        else throw new Error(`Fired a wrong actionname: ${key}. Available Actions: ${Object.keys(target)}`);
    }
};
const proxy = new Proxy(target, handler);
export default proxy;
